version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
